answers = [
           # yes like answers
           "Yes",
           "It is certain",
           "It is decidedly so",
           "Without a doubt",
           "Yes definitely",
           "You may rely on it",
           "As I see it yes",
           "Most likely",
           "Outlook good",
           "Signs point to yes",

           # no like answers
           "No",
           "My reply is no",
           "My sources say no",
           "Don't count on it",
           "Outlook not so good",
           "As I see it no",
           "Signs point to no",
           "Not likely",
           "Very doubtful",

           # bad answers
           "Reply hazy try again",
           "Ask again later",
           "Better not tell you now",
           "Cannot predict now",
           "Concentrate and ask again",
           ]

fortnite_locations = ["Tilted Towers",
                      "Anarchy Acres",
                      "Risky Reels",
                      "Wailing Woods",
                      "Loot Lake",
                      "Pleasant Park",
                      "Junk Junction",
                      "Haunted Hills",
                      "Snobby Shores",
                      "Salty Springs",
                      "Fatal Fields",
                      "Flush Factory",
                      "Lucky Landing",
                      "Moisty Mire",
                      "Lonely Lodge",
                      "Dusty Divot",
                      "Retail Row",
                      "Tomato Town",
                      "Greasy Grove",
                      "Shifty Shafts",
                      "Lucky Landing"]
